### ISSUE TITLE
Problem configuring PDP to use StaticRefPolicyProvider

### ISSUE THREAD

**Issue by jpcampb2** [authzforce/restful-pdp#1]
I am using the springboot example in this repo to experiment with a microservice-based PDP.

I am running into trouble when I try to modify the pdp.xml file to load additional policies and use the PolicySetIdReference feature. 
I have tried following the documentation here: https://github.com/authzforce/core/wiki/Policy-Providers

I note that the example pdp.xml says, "You may customize this PDP configuration except 'rootPolicyProvider' and 'refPolicyProvider' elements." but I don't know why or what exactly that means (there is no refPolicyProvider element in the example).

The configuration I am trying to use looks like the following:
```
   <refPolicyProvider id="refPolicyProvider" xsi:type="StaticRefPolicyProvider" policyLocation="policies/*.xml" />
   <rootPolicyProvider id="rootPolicyProvider" xsi:type="StaticRefBasedRootPolicyProvider">
      <policyRef>root</policyRef>
   </rootPolicyProvider>
```

The error I am getting is the following:
```
org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'pdpEngineConf' defined in class path resource [cxf-pdp-service.xml]: 
Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration]: 
Factory method 'getInstance' threw exception; nested exception is java.lang.IllegalArgumentException: 
Invalid PDP configuration file
...
Caused by: org.xml.sax.SAXParseException; 
systemId: file:/opt/authzforce/pdp.xml; lineNumber: 3; columnNumber: 115; 
cvc-complex-type.3.2.2: 
Attribute 'policyLocation' is not allowed to appear in element 'refPolicyProvider'.
```

I'm sure I'm missing some configuration setting and would love your insight.

**Comment by cdanger** [comment]
You have to check the XML schema to fix invalid configuration syntax like this. In this case, you are using StaticRefPolicyProvider. So you look for it in the table of [out-of-the-box policy providers](https://github.com/authzforce/core/wiki/Policy-Providers#out-of-the-box-policy-providers) you mentioned (the name is prefixed with XML namespace because all XML types have a namespace for uniqueness), then follow the link in the column _XML schema URL_. [There](https://github.com/authzforce/core/blob/master/pdp-engine/src/main/resources/pdp.xsd) you'll see that _policyLocation_ is an element and not an attribute, since there may be multiple ones. You will also see that the value must be either an absolute path written like a `file://` URL, or a relative path prefixed with `PARENT_DIR` property (auto-replaced with the absolute path of the configuration file's parent directory). So modify your configuration as follows:

```
...
<refPolicyProvider id="refPolicyProvider" xsi:type="StaticRefPolicyProvider">
  <policyLocation>${PARENT_DIR}/policies/*.xml</policyLocation>
</refPolicyProvider>
<rootPolicyProvider id="rootPolicyProvider" xsi:type="StaticRefBasedRootPolicyProvider">
   <policyRef>root</policyRef>
</rootPolicyProvider>
...
```
```

**Comment by jpcampb2** [comment]
Thank you for the quick reply and correction on my reading of the schema!

I was able to correctly instantiate the PDP with your fix, although I had to use multiple explicit policyLocation elements rather than the wildcard expansion. Thanks again!
