### ISSUE TITLE
Tomcat bug in Spring dependency of restful-pdp

### ISSUE THREAD

**Issue by 7opf** [authzforce/restful-pdp#6]
We are using this image https://hub.docker.com/r/authzforce/restful-pdp/tags (3.0.0) which has a dependency on spring boot 1.5.14.RELEASE which in turn has a dependency on tomcat 8.5.31. We are affected by the following bug in this version of tomcat: https://stackoverflow.com/a/51202547 and an upgrade to Spring boot 1.5.15 or higher would fix the issue for us – would you consider updating the JAR + docker image with updated dependencies to fix?

Regards
Severin

**Comment by cdanger** [comment]
If I upgrade to the latest Spring Boot 2.2.x or 2.3.0 which depends on Tomcat 9, is it still OK for you?

**Comment by 7opf** [comment]
Yes that should be fine, thank you.

**Comment by cdanger** [comment]
New docker image (3.1.0) just released. 

The new **Spring Boot** version is _only_ **2.1.13.RELEASE** for now, because the project depends on `cxf-spring-boot-starter-jaxrs` which depends on spring boot 2.1.13 in the last version (as of today). 

As for **Tomcat**, this Spring Boot version depends on **v9.0.31** now.
